// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvdtxlrdkimynkfwfupo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZHR4bHJka2lteW5rZndmdXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NzgyMzEsImV4cCI6MjA1MTI1NDIzMX0.DfUeV1Cxm2gTlfQ11O6ZuqvjYJwc-B0lYH7enxj_XG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);